### ISSUE TITLE
"stops" is not an array

### ISSUE THREAD

**Issue by viveleroi** [mistic100/tinygradient#42]
I was throwing together a repl.it test based on the example code, but running it throws the following error.

```
Error: "stops" is not an array
    at module.exports (/home/runner/ShallowOldlacePlot/node_modules/tinygradient/index.js:429:19)
    at /home/runner/ShallowOldlacePlot/index.js:3:18
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Code used:

```
const tinygradient = require('tinygradient');

const gradient = tinygradient([
  '#ff0000',
  '#00ff00',
  '#0000ff'
]);

const colorsRgb = gradient.hsv(9);
```

**Comment by mistic100** [comment]
I wonder if it is an isolated case of repl.it which someone has different prototypes of Array  
see this https://stackoverflow.com/a/22289982/1207670 for how "instanceof Array" works

Anyway I will replace it by "Array.isArray" and it will always work.

**Comment by mistic100** [comment]
1.1.5 published
